server:
  port: 8803
  servlet:
    context-path: /deal

http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000
#\u6570\u636E\u5E93\u914D\u7F6E
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.50.5:3306/abc?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: 123456

#mybatis-plus\u914D\u7F6E
mybatis-plus:
  # \u5982\u679C\u662F\u653E\u5728src/main/java\u76EE\u5F55\u4E0B classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # \u5982\u679C\u662F\u653E\u5728resource\u76EE\u5F55 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:mapper/*Mapper.xml
  #\u5B9E\u4F53\u626B\u63CF\uFF0C\u591A\u4E2Apackage\u7528\u9017\u53F7\u6216\u8005\u5206\u53F7\u5206\u9694
  typeAliasesPackage: com.gem.entity
  global-config:

    id-type: 0

    field-strategy: 0

    logic-delete-value: 1
    logic-not-delete-value: 0

  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    #\u914D\u7F6E\u8FD4\u56DE\u6570\u636E\u5E93(column\u4E0B\u5212\u7EBF\u547D\u540D&&\u8FD4\u56DEjava\u5B9E\u4F53\u662F\u9A7C\u5CF0\u547D\u540D)\uFF0C\u81EA\u52A8\u5339\u914D\u65E0\u9700as\uFF08\u6CA1\u5F00\u542F\u8FD9\u4E2A\uFF0CSQL\u9700\u8981\u5199as\uFF1A select user_id as userId\uFF09
    #    map-underscore-to-camel-case: true
    cache-enabled: true

#    #\u914D\u7F6EJdbcTypeForNull, oracle\u6570\u636E\u5E93\u5FC5\u987B\u914D\u7F6E
#    jdbc-type-for-null: 'null'
swagger:
  enabled: true